#!/bin/bash
#
# GTK Integration модуль
# Полная интеграция GTK3/GTK4 с цветовыми схемами Noctalia
#

install_gtk-integration() {
    log_info "=== Установка GTK3/GTK4 интеграции ==="

    # Установка GTK пакетов
    local gtk_packages=(
        "gtk3"
        "gtk4"
        "libadwaita"
        "qalculate-gtk"  # Для тестирования GTK3
        "gnome-calculator"  # Для тестирования GTK4
    )

    log_info "Установка GTK пакетов..."

    for pkg in "${gtk_packages[@]}"; do
        if ! pacman -Qi "$pkg" &>/dev/null; then
            log_info "Установка $pkg..."
            sudo pacman -S --noconfirm "$pkg" 2>&1 | tee -a "$LOG_FILE"
        else
            log_info "✓ $pkg уже установлен"
        fi
    done

    # Копирование конфигураций GTK
    log_info "Копирование конфигураций GTK..."

    # GTK3
    if [[ -d "$CONFIG_DIR/gtk-3.0" ]]; then
        mkdir -p "$HOME/.config/gtk-3.0"
        cp -r "$CONFIG_DIR/gtk-3.0/"* "$HOME/.config/gtk-3.0/"

        # Установка темы Noctalia
        sed -i 's/gtk-theme-name=.*/gtk-theme-name=Noctalia/' "$HOME/.config/gtk-3.0/settings.ini" 2>/dev/null || \
            echo "gtk-theme-name=Noctalia" >> "$HOME/.config/gtk-3.0/settings.ini"

        log "✓ Конфигурация GTK3 скопирована"
    fi

    # GTK4
    if [[ -d "$CONFIG_DIR/gtk-4.0" ]]; then
        mkdir -p "$HOME/.config/gtk-4.0"
        cp -r "$CONFIG_DIR/gtk-4.0/"* "$HOME/.config/gtk-4.0/"

        log "✓ Конфигурация GTK4 скопирована"
    fi

    # Создание GTK3 темы Noctalia
    create_gtk3_theme

    # Настройка gsettings
    configure_gtk_settings

    # Проверка настроек
    verify_gtk_config

    log "✓ GTK интеграция завершена"
}

create_gtk3_theme() {
    log_info "Создание GTK3 темы Noctalia..."

    local theme_dir="$HOME/.themes/Noctalia/gtk-3.0"
    mkdir -p "$theme_dir"

    # Создание базового gtk.css
    # (Этот файл будет перезаписываться Noctalia при смене цветовой схемы)

    cat > "$theme_dir/gtk.css" << 'EOF'
/* Noctalia GTK3 Theme - Auto-generated */
/* This file is automatically regenerated by Noctalia Shell */
/* Do not edit manually - changes will be overwritten */

/* Default colors (will be replaced by Noctalia) */
window {
    background-color: #f2ecbc;
    color: #000000;
}

.background {
    background-color: #f2ecbc;
}

button {
    background-image: none;
    background-color: #6f894e;
    color: #e6e1e5;
}

button:hover {
    background-color: #c1cab4;
}

entry {
    background-color: #efe7ab;
    color: #000000;
}

.view, textview text {
    background-color: #f2ecbc;
    color: #000000;
}
EOF

    log "✓ GTK3 тема Noctalia создана в $theme_dir"
}

configure_gtk_settings() {
    log_info "Настройка GTK через gsettings..."

    # Установка темы
    gsettings set org.gnome.desktop.interface gtk-theme "Noctalia" 2>/dev/null || log_warn "Не удалось установить gtk-theme"

    # Установка иконочной темы
    gsettings set org.gnome.desktop.interface icon-theme "Papirus-Dark" 2>/dev/null || log_warn "Не удалось установить icon-theme"

    # Установка темы курсора
    gsettings set org.gnome.desktop.interface cursor-theme "capitaine-cursors" 2>/dev/null || true

    # Установка цветовой схемы (для GTK4/libadwaita)
    gsettings set org.gnome.desktop.interface color-scheme "prefer-light" 2>/dev/null || log_warn "Не удалось установить color-scheme"

    log "✓ gsettings настроены"
}

verify_gtk_config() {
    log_info "Проверка конфигурации GTK..."

    local issues=0

    # Проверка GTK3 settings.ini
    if [[ -f "$HOME/.config/gtk-3.0/settings.ini" ]]; then
        if grep -q "gtk-theme-name=Noctalia" "$HOME/.config/gtk-3.0/settings.ini"; then
            log "✓ GTK3: gtk-theme-name=Noctalia установлен"
        else
            log_warn "GTK3: gtk-theme-name НЕ установлен в Noctalia"
            issues=$((issues + 1))
        fi

        if grep -q "gtk-icon-theme-name=Papirus-Dark" "$HOME/.config/gtk-3.0/settings.ini"; then
            log "✓ GTK3: иконочная тема Papirus-Dark установлена"
        else
            log_warn "GTK3: иконочная тема не установлена"
        fi
    fi

    # Проверка GTK3 темы
    if [[ -d "$HOME/.themes/Noctalia/gtk-3.0" ]]; then
        log "✓ GTK3 тема Noctalia существует"
    else
        log_error "GTK3 тема Noctalia НЕ найдена!"
        issues=$((issues + 1))
    fi

    # Проверка gsettings
    local current_theme=$(gsettings get org.gnome.desktop.interface gtk-theme 2>/dev/null | tr -d "'")
    if [[ "$current_theme" == "Noctalia" ]]; then
        log "✓ gsettings: gtk-theme = Noctalia"
    else
        log_warn "gsettings: gtk-theme = $current_theme (ожидалось Noctalia)"
    fi

    local current_color_scheme=$(gsettings get org.gnome.desktop.interface color-scheme 2>/dev/null | tr -d "'")
    log_info "gsettings: color-scheme = $current_color_scheme"

    if [[ $issues -gt 0 ]]; then
        log_warn "Обнаружены проблемы в конфигурации GTK ($issues)"
        log_warn "GTK приложения могут не подхватывать цветовые схемы!"
    else
        log "✓ Конфигурация GTK проверена, проблем не обнаружено"
    fi
}
